CREATE TABLE ETUDIANT (
    CodeE INT PRIMARY KEY,

    NomE VARCHAR(30) NOT NULL,
    DatnE DATE NOT NULL
);




CREATE TABLE MATIERE (
    CodeMt INT PRIMARY KEY,

    NomMt VARCHAR(15) NOT NULL,
    CoefMt INT NOT NULL
);





CREATE TABLE NOTE (
    CodeE INT REFERENCES ETUDIANT(codeE) ON DELETE CASCADE,
    CodeEns INT REFERENCES ENSEIGNANT(CodeEns) ON DELETE CASCADE,

    Note DECIMAL(5,2) CHECK (Note >= 0 AND Note <= 20),

);






CREATE TABLE ENSEIGNANT (
    CodeEns INT PRIMARY KEY,

    NomEns VARCHAR(30) NOT NULL,
    GradeEns VARCHAR(20),

    CodeMt INT REFERENCES ETUDIANT(codeMt) ON DELETE CASCADE
);
